### ISSUE TITLE
关于实现校园网自动登录的脚本

### ISSUE THREAD

**Issue by Rock-L21** [Erven2016/erven2016.github.io#1]
请问实现校园网自动登录的脚本还有么，我看济南大学的repo已经没了。

**Comment by Rock-L21** [comment]
1-实现校园网自动登录的方法（临大联通）.md 这篇文章的图片也无法正常显示。。。

**Comment by Erven2016** [comment]
你好，我这里图片加载正常，cos 设置了防盗链，需要提供 referer 才能加载，可以从[博客链接](https://blog.erven2016.com/post/1-%E5%AE%9E%E7%8E%B0%E6%A0%A1%E5%9B%AD%E7%BD%91%E8%87%AA%E5%8A%A8%E7%99%BB%E5%BD%95%E7%9A%84%E6%96%B9%E6%B3%95%E4%B8%B4%E5%A4%A7%E8%81%94%E9%80%9A/)进入。

可以试试下面这个脚本（首先看看宿舍的校园网连接后是否会跳到这个[页面](http://139.198.3.98/sdjd)），但不保证能直接用，可能得自己调试，路由器必须安装 OpenWRT 以及 curl 包。
```shell
#!/bin/ash
# 路由器需要安装 OpenWRT，以及 curl 包

# 用户信息
school_id="" # 学校代码
username="" # 一般是手机号
password="" # 密码
basip="" # 看看校园网跳转网页的链接中有无这个参数

portal_url="http://139.198.3.98/sdjd"

function getCookies() {
    ms_time="$(($(date +%s%N) / 1000000))"
    url="http://www.126.com/?time=$ms_time"
    curl -A "$user_agent" \
        -H "Accept-Language: en-US,en;q=0.8" \
        -H "Connection: Keep-Alive" \
        -H "Accept-Encoding: gzip" \
        -H "Accept-Encoding: gzip" \
        -b $(dirname $0)/.cookies -c $(dirname $0)/.cookies \
        -L -v "$url"
}

function restartInterfaceWAN() {
	echo "restarting interface WAN"
    ifdown wan
    sleep 3s
    ifup wan
    sleep 10s
}

function getWlanIPAddress() {
    . /lib/functions/network.sh
    network_get_ipaddr ip wan
    echo $ip
}

function chknetwork() {
	# 检测是否能连接上互联网（暂时没调用，懒得改）
    timeout=5
    target=www.baidu.com
    ret_code=$(curl -I -s --connect-timeout $timeout $target -w %{http_code} | tail -n1)
    if [ "x$ret_code" = "x200" ]; then
        echo 1
    else
        echo 0
    fi
}

function heartbeat() {
	# 心跳包保活，如果经常无故掉线，可以调用这个试试
    echo "sending heartbeat"
    curl -A "$user_agent" \
        -H "Pragma:no-cache" -H "Cache-Control:no-cache" -H "Referer:http://139.198.3.98/sdjd/protalAction!toSuccess.action" \
        -H "Accept-Encoding:gzip,deflate" -H "Accept-Language:en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4" \
        -H "Accept: application/json, text/javascript, */*" -b $(dirname $0)/.cookies \
        -v $portal_url
    curl -v "http://www.baidu.com/" >/dev/null
    echo "sent"
}

function login() {
    restartInterfaceWAN
    ip=$(getWlanIPAddress)
    getCookies
    data_pattern="school_id=$school_id&lpsUserName=$username&lpsPwd=$password&wlanuserip=$ip&basip=$basip"
    url="$portal_url/services/portal/portalAuth"
	# 发送请求，结果返回输出到脚本目录下的 login_result.json 文件
	# 一般含有 success:true 即登陆成功
    curl -A "$user_agent" \
        -H 'Accept-Language: en-US,en;q=0.8' \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        -H 'Connection: Keep-Alive' -H 'Accept-Encoding: gzip' \
        -d "$data_pattern" \
        -b $(dirname $0)/.cookies \
        -s -o $(dirname $0)/login_result.json "$url"
}

login
```

**Comment by Rock-L21** [comment]
@Erven2016 十分感谢.

**Comment by Rock-L21** [comment]
请问,在发送curl命令后 已经有回复了而且验证成功了,但还是上不去网,请问是需要PPPOE么...

**Comment by Erven2016** [comment]
可以看一下 login_result.json 吗，像这样

![image](https://user-images.githubusercontent.com/18652605/160231681-2af14c03-ad56-4ab5-afe9-755c45b312af.png)

**Comment by Rock-L21** [comment]
您好，{"msg":"登录失败重新连接 WiFi !","success":false} ，以上是输出的login_result.json

**Comment by Rock-L21** [comment]
RockL@DESKTOP-OU14R1E MINGW64 ~/Desktop
$ sh login.sh
restarting interface WAN
login.sh: line 26: ifdown: command not found
login.sh: line 28: ifup: command not found
login.sh: line 33: /lib/functions/network.sh: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 123.126.96.181:80...
* Connected to www.126.com (123.126.96.181) port 80 (#0)
> GET /?time=1648299255808 HTTP/1.1
> Host: www.126.com
> Accept: */*
> Accept-Language: en-US,en;q=0.8
> Connection: Keep-Alive
> Accept-Encoding: gzip
> Accept-Encoding: gzip
>
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Moved Temporarily
< Allow: GET,POST,HEAD
< MIME-Version: 1.0
< Server: NetEngine Server 1.0
< Pragma: No-Cache
< Location: http://139.198.3.98:80/sdjd?wlanuserip=10.177.28.251&wlanacname=SDJN-XZ-ME60-B2&basip=124.128.40.39
<
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
* Issue another request to this URL: 'http://139.198.3.98:80/sdjd?wlanuserip=10.177.28.251&wlanacname=SDJN-XZ-ME60-B2&basip=124.128.40.39'
*   Trying 139.198.3.98:80...
* Connected to 139.198.3.98 (139.198.3.98) port 80 (#1)
> GET /sdjd?wlanuserip=10.177.28.251&wlanacname=SDJN-XZ-ME60-B2&basip=124.128.40.39 HTTP/1.0
> Host: 139.198.3.98
> Accept: */*
> Accept-Language: en-US,en;q=0.8
> Connection: Keep-Alive
> Accept-Encoding: gzip
> Accept-Encoding: gzip
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302
< Server: Tengine
< Date: Sat, 26 Mar 2022 12:54:16 GMT
< Connection: close
< Location: http://139.198.3.98/sdjd/?wlanuserip=10.177.28.251&wlanacname=SDJN-XZ-ME60-B2&basip=124.128.40.39
* Added cookie route="74f51685c56f1c432de12cf91a407795" for domain 139.198.3.98, path /, expire 0
< Set-Cookie: route=74f51685c56f1c432de12cf91a407795;Path=/
< X-Frame-Options: SAMEORIGIN
<
{ [0 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 1
* Issue another request to this URL: 'http://139.198.3.98/sdjd/?wlanuserip=10.177.28.251&wlanacname=SDJN-XZ-ME60-B2&basip=124.128.40.39'
* Hostname 139.198.3.98 was found in DNS cache
*   Trying 139.198.3.98:80...
* Connected to 139.198.3.98 (139.198.3.98) port 80 (#2)
> GET /sdjd/?wlanuserip=10.177.28.251&wlanacname=SDJN-XZ-ME60-B2&basip=124.128.40.39 HTTP/1.0
> Host: 139.198.3.98
> Accept: */*
> Cookie: route=74f51685c56f1c432de12cf91a407795
> Accept-Language: en-US,en;q=0.8
> Connection: Keep-Alive
> Accept-Encoding: gzip
> Accept-Encoding: gzip
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200
< Server: Tengine
< Date: Sat, 26 Mar 2022 12:54:16 GMT
< Content-Type: text/html;charset=UTF-8
< Content-Length: 945
< Connection: keep-alive
* Added cookie JSESSIONID="2790A2F9C37CCF8F97947DE0E36E9DE0" for domain 139.198.3.98, path /sdjd, expire 0
< Set-Cookie: JSESSIONID=2790A2F9C37CCF8F97947DE0E36E9DE0; Path=/sdjd; HttpOnly
< X-Frame-Options: SAMEORIGIN
<
{ [945 bytes data]
100   945  100   945    0     0   5175      0 --:--:-- --:--:-- --:--:--  5175





<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
        <head>
                <base href="http://139.198.3.98:80/sdjd">



<title></title>



                <meta http-equiv="pragma" content="no-cache">
                <meta http-equiv="cache-control" content="no-cache">
                <meta http-equiv="expires" content="0">
                <meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
                <meta http-equiv="description" content="This is my page">
                
                <script type="text/javascript" src="http://139.198.3.98:80/sdjd/resources/js/jquery-1.11.1.min.js"></script>
                <script type="text/javascript" src="http://139.198.3.98:80/sdjd/resources/js/jquery.cookie.js"></script>
                <script type="text/javascript">

                 window.location.href="http://139.198.3.98:80/sdjd/protalAction!index.action?wlanuserip=10.177.28.251&basip=124.128.40.39";
                </SCRIPT>

        </head>

</html>

* Connection #2 to host 139.198.3.98 left intact

**Comment by Rock-L21** [comment]
以上是运行您提供的脚本，所输出的所有内容，我发现在连上WIFI未登录但浏览器主动弹出以下链接(http://139.198.3.98/sdjd/protalAction!index.action?wlanuserip=10.177.28.251&basip=124.128.40.39)时，还有wlanuserip这个参数，是否也应该加上(脚本里没加上)呢

**Comment by Erven2016** [comment]
看起来你运行在 Windows 系统的 MINGW64 SHELL 环境中，我提供的这个脚本是运行在路由器的 OpenWRT 系统上的，Windows 上跑不了。

Windows 并不能使用网页 portal 进行登录哦（我问过安装宽带的小哥，只有 MacOS 和 Linux 可以网页登录）。


 
以上是运行您提供的脚本，所输出的所有内容，我发现在连上WIFI未登录但浏览器主动弹出以下链接

>以及这个问题，wlanuserip参数已经加上了，302重定向很正常
([http://139.198.3.98/sdjd/protalAction!index.action?wlanuserip=10.177.28.251&basip=124.128.40.39)时，还有wlanuserip这个参数，是否也应该加上(脚本里没加上)呢](http://139.198.3.98/sdjd/protalAction!index.action?wlanuserip=10.177.28.251&basip=124.128.40.39)%E6%97%B6%EF%BC%8C%E8%BF%98%E6%9C%89wlanuserip%E8%BF%99%E4%B8%AA%E5%8F%82%E6%95%B0%EF%BC%8C%E6%98%AF%E5%90%A6%E4%B9%9F%E5%BA%94%E8%AF%A5%E5%8A%A0%E4%B8%8A(%E8%84%9A%E6%9C%AC%E9%87%8C%E6%B2%A1%E5%8A%A0%E4%B8%8A)%E5%91%A2)

**Comment by Erven2016** [comment]
Windows 可以尝试这个命令，记得先创建一个名称是 dial 的拨号连接，或者你自己改称别的也行，命令里连接名字要对应。

至于账号后缀`@dxcwo201`，我也不确定这个系统的各学校使用的账号后缀是不是一样的。

```bat
rasdial dial 账户@dxcwo201 密码
```

**Comment by Erven2016** [comment]
济南大学请参考[这篇博客](https://blog.sparta-en.org/2020/09/03/%E6%B5%8E%E5%8D%97%E5%A4%A7%E5%AD%A6%E5%AE%BF%E8%88%8D%E8%81%94%E9%80%9A%E6%89%8B%E5%8A%A8PPPoE%E4%B8%8A%E7%BD%91/)

**Comment by Rock-L21** [comment]
好的 大体思路明白了，我再试试，再次感谢您。
